web:
  image: nginx
  volumes:
   - ./nginx/conf.d/https.conf:/etc/nginx/conf.d/https.conf
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/sites-available:/etc/nginx/sites-available
   - ./keys:/etc/ssl/certs
  ports:
   - "80:80"
   - "443:443"
  
